import fs from 'fs';
import path from 'path';
import { Convert } from '../../generated/Stig';
import { StigWrapper } from '../Stig';
import { toLibraryStig } from '../upload';

/**
 * Contract tests for the converted CIS Benchmark library files
 * (generated by scripts/cis/). The output must behave like any DISA
 * STIG: same yq-shaped JSON contract, same manifest semantics, profiles
 * grouped under the Public classification so StigView renders them.
 */

const schemaDir = path.join(
    __dirname,
    '../../../../public/data/stigs/schema'
);

const cisManifest = (
    JSON.parse(
        fs.readFileSync(
            path.join(__dirname, '../../../../public/data/stigs/manifest.json'),
            'utf8'
        )
    ) as Array<{ id: string }>
).filter((entry) => entry.id.startsWith('CIS_'));

const cisFiles = fs
    .readdirSync(schemaDir)
    .filter((f) => f.endsWith('.json') && f.startsWith('CIS_'))
    .sort();

describe('converted CIS benchmarks', () => {
    it('are present in the manifest and on disk', () => {
        expect(cisFiles.length).toBeGreaterThan(0);
        expect(cisManifest.map((entry) => entry.id)).toEqual(
            cisFiles.map((file) => file.replace('.json', ''))
        );
    });

    it.each(cisFiles)('%s feeds the app contract', (file) => {
        const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
        const stig = new StigWrapper(Convert.toStig(json));

        expect(stig.id).toBeTruthy();
        expect(stig.title).toContain('CIS');
        expect(stig.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
        expect(stig.version).toMatch(/^\d+\.\d+/);
        expect(stig.publisher).toBe('Center for Internet Security');
        expect(stig.groups.length).toBeGreaterThan(0);

        // Profiles must land under the Public classification tab and
        // select a subset of the benchmark's groups.
        expect(Object.keys(stig.rawProfilesByClassification)).toContain(
            'Public'
        );
        const profiles = stig.profiles;
        expect(profiles.length).toBeGreaterThan(0);
        const groupIds = new Set(stig.groups.map((group) => group.id));
        for (const profile of profiles) {
            expect(profile.select.length).toBeGreaterThan(0);
            for (const select of profile.select) {
                expect(groupIds.has(select.id)).toBe(true);
            }
        }

        // Every rule carries the fields the UI and checklist editor need.
        for (const group of stig.groups) {
            expect(group.id).toMatch(/^V-/);
            expect(group.rule.id).toMatch(/^SV-/);
            expect(group.rule.title).toBeTruthy();
            expect(['high', 'medium', 'low', 'info']).toContain(
                group.rule.severity
            );
            // Empty Remediation sections exist upstream (flagged by the
            // converter report); the field itself must be present.
            expect(group.rule.fixText).toBeDefined();
            expect(group.rule.description).toBeTruthy();
            expect(group.rule.version).toMatch(/^\d+(\.\d+)*$/);
            // A few upstream recommendations ship an empty Audit section
            // (e.g. PostgreSQL 7.3 — flagged by the converter report);
            // the field must exist, its content mirrors the document.
            expect(group.rule.check).toBeDefined();
        }
    });

    /**
     * The XML↔JSON equivalence contract is pinned by
     * src/api/__tests__/xccdf.spec.ts (the site serializes JSON to XCCDF
     * in-browser; no committed .xml copy exists anymore).
     */

    it('produce library metadata matching the manifest', () => {
        for (const file of cisFiles) {
            const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
            const entry = toLibraryStig(
                '',
                Convert.toStig(json),
                0
            );
            const expected = cisManifest.find((m) => m.id === entry.stig_id);
            expect(expected).toBeDefined();
            expect(entry.title).toBe(expected!.title);
            expect(entry.description).toBe(expected!.description);
            expect(entry.version).toBe(expected!.version);
            expect(entry.date).toBe(expected!.date);
        }
    });

    it('rule ids are unique within each benchmark', () => {
        // DISA/CIS reuse SV ids ACROSS benchmarks, so uniqueness is only
        // enforced per file.
        for (const file of cisFiles) {
            const ids = new Set<string>();
            const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
            const stig = Convert.toStig(json);
            const groups = Array.isArray(stig.Benchmark.Group)
                ? stig.Benchmark.Group
                : [stig.Benchmark.Group];
            for (const group of groups) {
                const id = group.Rule['+@id'];
                expect(ids.has(id)).toBe(false);
                ids.add(id);
            }
        }
    });
});
