import fs from 'fs';
import path from 'path';
import { Convert } from '../../generated/Stig';
import { StigWrapper } from '../Stig';
import { convertXccdf, toLibraryStig } from '../upload';

/**
 * Contract tests for the converted CIS Benchmark library files
 * (generated by scripts/cis/). The output must behave like any DISA
 * STIG: same yq-shaped JSON contract, same manifest semantics, profiles
 * grouped under the Public classification so StigView renders them.
 */

const schemaDir = path.join(
    __dirname,
    '../../../../public/data/stigs/schema'
);

const cisManifest = (
    JSON.parse(
        fs.readFileSync(
            path.join(__dirname, '../../../../public/data/stigs/manifest.json'),
            'utf8'
        )
    ) as Array<{ id: string }>
).filter((entry) => entry.id.startsWith('CIS_'));

const cisFiles = fs
    .readdirSync(schemaDir)
    .filter((f) => f.endsWith('.json') && f.startsWith('CIS_'))
    .sort();

describe('converted CIS benchmarks', () => {
    it('are present in the manifest and on disk', () => {
        expect(cisFiles.length).toBeGreaterThan(0);
        expect(cisManifest.map((entry) => entry.id)).toEqual(
            cisFiles.map((file) => file.replace('.json', ''))
        );
    });

    it.each(cisFiles)('%s feeds the app contract', (file) => {
        const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
        const stig = new StigWrapper(Convert.toStig(json));

        expect(stig.id).toBeTruthy();
        expect(stig.title).toContain('CIS');
        expect(stig.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
        expect(stig.version).toMatch(/^\d+\.\d+/);
        expect(stig.publisher).toBe('Center for Internet Security');
        expect(stig.groups.length).toBeGreaterThan(0);

        // Profiles must land under the Public classification tab and
        // select a subset of the benchmark's groups.
        expect(Object.keys(stig.rawProfilesByClassification)).toContain(
            'Public'
        );
        const profiles = stig.profiles;
        expect(profiles.length).toBeGreaterThan(0);
        const groupIds = new Set(stig.groups.map((group) => group.id));
        for (const profile of profiles) {
            expect(profile.select.length).toBeGreaterThan(0);
            for (const select of profile.select) {
                expect(groupIds.has(select.id)).toBe(true);
            }
        }

        // Every rule carries the fields the UI and checklist editor need.
        for (const group of stig.groups) {
            expect(group.id).toMatch(/^V-/);
            expect(group.rule.id).toMatch(/^SV-/);
            expect(group.rule.title).toBeTruthy();
            expect(['high', 'medium', 'low', 'info']).toContain(
                group.rule.severity
            );
            expect(group.rule.check).toBeTruthy();
            expect(group.rule.fixText).toBeTruthy();
            expect(group.rule.description).toBeTruthy();
            expect(group.rule.version).toMatch(/^\d+(\.\d+)*$/);
        }
    });

    it.each(cisFiles)('%s XML mirrors the committed JSON', (file) => {
        const xml = fs.readFileSync(
            path.join(schemaDir, file.replace('.json', '.xml')),
            'utf8'
        );
        const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
        const converted = convertXccdf(xml);

        // Canonicalize singleton arrays (Group/Profile arrayification,
        // yq null vs fast-xml-parser ""), the same terms upload.spec.ts
        // pins the DISA library with.
        const canonicalize = (value: unknown): unknown => {
            if (Array.isArray(value)) return value.map(canonicalize);
            if (value && typeof value === 'object') {
                return Object.keys(value as Record<string, unknown>)
                    .sort()
                    .reduce((acc, key) => {
                        acc[key] = canonicalize(
                            (value as Record<string, unknown>)[key]
                        );
                        return acc;
                    }, {} as Record<string, unknown>);
            }
            return value === null ? '' : value;
        };
        expect(canonicalize(converted)).toEqual(canonicalize(JSON.parse(json)));
    });

    it('produce library metadata matching the manifest', () => {
        for (const file of cisFiles) {
            const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
            const entry = toLibraryStig(
                '',
                Convert.toStig(json),
                0
            );
            const expected = cisManifest.find((m) => m.id === entry.stig_id);
            expect(expected).toBeDefined();
            expect(entry.title).toBe(expected!.title);
            expect(entry.description).toBe(expected!.description);
            expect(entry.version).toBe(expected!.version);
            expect(entry.date).toBe(expected!.date);
        }
    });

    it('rule ids are unique across the CIS library', () => {
        const ids = new Set<string>();
        for (const file of cisFiles) {
            const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
            const stig = Convert.toStig(json);
            const groups = Array.isArray(stig.Benchmark.Group)
                ? stig.Benchmark.Group
                : [stig.Benchmark.Group];
            for (const group of groups) {
                const id = group.Rule['+@id'];
                expect(ids.has(id)).toBe(false);
                ids.add(id);
            }
        }
    });
});
