import fs from 'fs';
import path from 'path';
import { Convert } from '../../generated/Stig';
import { StigWrapper } from '../Stig';
import { toLibraryStig } from '../upload';

/**
 * Contract tests for the converted CISA ScubaGear baseline library
 * files (generated by scripts/scuba/). The output must behave like any
 * DISA STIG: same yq-shaped JSON contract, same manifest semantics,
 * profiles grouped under the Public classification so StigView renders
 * them. Rule identity keys on the version-less CISA policy number
 * (group id V-<sha256(MS.AAD.1.1)>), so policy version bumps diff as
 * modified rules.
 */

const schemaDir = path.join(
    __dirname,
    '../../../../public/data/stigs/schema'
);

const cisaManifest = (
    JSON.parse(
        fs.readFileSync(
            path.join(__dirname, '../../../../public/data/stigs/manifest.json'),
            'utf8'
        )
    ) as Array<{ id: string }>
).filter((entry) => entry.id.startsWith('CISA_'));

const cisaFiles = fs
    .readdirSync(schemaDir)
    .filter((f) => f.endsWith('.json') && f.startsWith('CISA_'))
    .sort();

describe('converted CISA ScubaGear baselines', () => {
    it('are present in the manifest and on disk', () => {
        expect(cisaFiles.length).toBe(7);
        expect(cisaManifest.map((entry) => entry.id)).toEqual(
            cisaFiles.map((file) => file.replace('.json', ''))
        );
    });

    it.each(cisaFiles)('%s feeds the app contract', (file) => {
        const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
        const stig = new StigWrapper(Convert.toStig(json));

        expect(stig.id).toMatch(/^CISA_/);
        expect(stig.title).toContain('CISA M365 Secure Configuration Baseline');
        expect(stig.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
        // Version is the ScubaGear release the content came from.
        expect(stig.version).toMatch(/^\d+\.\d+\.\d+$/);
        expect(stig.publisher).toBe('CISA');
        expect(stig.groups.length).toBeGreaterThan(0);

        // Profiles must land under the Public classification tab and
        // cover the benchmark's groups.
        expect(Object.keys(stig.rawProfilesByClassification)).toContain(
            'Public'
        );
        const profiles = stig.profiles;
        expect(profiles.length).toBeGreaterThan(0);
        const groupIds = new Set(stig.groups.map((group) => group.id));
        const selected = new Set(
            profiles.flatMap((profile) =>
                profile.select.map((select) => select.id)
            )
        );
        for (const groupId of groupIds) {
            expect(selected.has(groupId)).toBe(true);
        }

        // Every rule carries the fields the UI and checklist editor
        // need; identity keys on the CISA policy id.
        for (const group of stig.groups) {
            expect(group.id).toMatch(/^V-/);
            expect(group.rule.id).toMatch(/^SV-/);
            expect(group.rule.title).toBeTruthy();
            expect(['high', 'medium', 'low', 'info']).toContain(
                group.rule.severity
            );
            expect(group.rule.fixText).toBeDefined();
            expect(group.rule.description).toBeTruthy();
            // Full policy id, e.g. MS.AAD.3.3v2.
            expect(group.rule.version).toMatch(
                /^MS\.[A-Z]+\.\d+\.\d+v\d+$/
            );
            // Group ids hash the version-less policy number, so a
            // v1 -> v2 policy bump stays matched for migration/diffs.
            const policyNumber = group.rule.version.replace(/v\d+$/, '');
            expect(group.id).toBe(`V-${policyGroupDigest(policyNumber)}`);
            expect(group.rule.check).toBeDefined();
        }
    });

    it('produce library metadata matching the manifest', () => {
        for (const file of cisaFiles) {
            const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
            const entry = toLibraryStig('', Convert.toStig(json), 0);
            const expected = cisaManifest.find((m) => m.id === entry.stig_id);
            expect(expected).toBeDefined();
            expect(entry.title).toBe(expected!.title);
            expect(entry.description).toBe(expected!.description);
            expect(entry.version).toBe(expected!.version);
            expect(entry.date).toBe(expected!.date);
        }
    });

    it('rule ids are unique within each benchmark', () => {
        for (const file of cisaFiles) {
            const ids = new Set<string>();
            const json = fs.readFileSync(path.join(schemaDir, file), 'utf8');
            const stig = Convert.toStig(json);
            const groups = Array.isArray(stig.Benchmark.Group)
                ? stig.Benchmark.Group
                : [stig.Benchmark.Group];
            for (const group of groups) {
                const id = group.Rule['+@id'];
                expect(ids.has(id)).toBe(false);
                ids.add(id);
            }
        }
    });
});

/** Mirrors scripts/scuba/scuba_converter/map.py stable_hash. */
function policyGroupDigest(policyNumber: string): string {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const crypto = require('crypto') as typeof import('crypto');
    return crypto
        .createHash('sha256')
        .update(policyNumber)
        .digest('hex')
        .slice(0, 8)
        .toUpperCase();
}
